services:
  db:
    image: mariadb:latest
    container_name: media-matter-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: media
    volumes:
      - media_matter_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  ftp:
    image: garethflowers/ftp-server:latest
    container_name: media-matter-ftp
    restart: always
    environment:
      - PUBLIC_IP=192.168.0.1
      - FTP_PASS=123
      - FTP_USER=user
    ports:
      - "20-21:20-21/tcp"
      - "40000-40009:40000-40009/tcp"
    volumes:
      - media_matter_ftp_data:/home/user

volumes:
  media_matter_db_data:
  media_matter_ftp_data:
