services:
  db:
    image: mariadb:latest
    container_name: media-matter-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: media
    volumes:
      - media_matter_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  minio:
    image: minio/minio
    volumes:
      - media_matter_minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
      MINIO_VOLUMES: /data
    command: minio server --console-address ":9001"

volumes:
  media_matter_db_data:
  media_matter_minio_data:
