services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: media
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  ftp:
    image: delfer/alpine-ftp-server:latest
    container_name: ftp_server
    restart: always
    environment:
      USERS: "testuser:testpass:1000"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ftp_data:/home/testuser

volumes:
  db_data:
  ftp_data:
